apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
      - name: postgres
        image: postgres:12.1-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: cast-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cast-db-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: cast-db-secret
              key: database
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db
  namespace: dev
spec:
  selector:
    app: cast-db
  ports:
  - port: 5432
    targetPort: 5432
